FROM node:24-alpine3.20 AS build

# ARG PORT
# ENV PORT=${PORT}

WORKDIR /app

COPY ./client/package*.json ./

RUN yarn install

COPY ./client ./

RUN yarn build

EXPOSE 4000

CMD ["npm", "run", "serve:ssr:app"]
