FROM node:20-slim AS build

WORKDIR /app
COPY ./server/package.json ./
RUN yarn install
COPY ./server ./

RUN yarn build

FROM node:20-slim
WORKDIR /app
COPY --from=build /app/dist ./
COPY --from=build /app/node_modules ./node_modules
EXPOSE 4931
CMD ["node", "index.js"]
