FROM node:22-alpine3.20 AS build

ARG PORT
ENV PORT=${PORT}

WORKDIR /app

COPY ./client/package*.json ./

RUN npm install

COPY ./client ./

RUN npm run build --prod

EXPOSE 80

CMD ["npm", "run", "serve:ssr:app"]