FROM node:20-slim

ARG DB_URL
ENV DB_URL=${DB_URL}

# ARG MULTER_UPLOAD_DIR: "/app/uploads"
# ENV MULTER_UPLOAD_DIR="/app/uploads"

# ARG FILE_STORAGE_DIR: "/app/files"
# ENV FILE_STORAGE_DIR="/app/files"

# RUN apt-get update && apt-get install -y git && rm -rf /var/lib/apt/lists/*

# RUN git config --global user.email "temp@example.com" && git config --global user.name "Temp User"

WORKDIR /app

COPY ./server.js/package*.json ./

RUN npm install -g yarn

RUN yarn install

COPY ./server.js ./

EXPOSE 4931

CMD ["yarn", "start"]
