FROM node:22-alpine3.20 AS build

WORKDIR /app

COPY ./client/package*.json ./

RUN npm install --legacy-peer-deps

COPY ./client ./

RUN npm run build --prod

FROM nginx:alpine

RUN rm -rf /etc/nginx/conf.d/default.conf

COPY nginx.conf /etc/nginx/conf.d/default.conf

COPY --from=build /app/dist /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
