export const programmes = [
  {
    "id": "a1b2c3d4-e5f6-7890-1234-567890abcdef",
    "faculty": "Faculty of Computing and Informatics",
    "name": "Bachelor of Science in Computer Science",
    "createdDate": "2023-01-15",
    "lastReviewDate": "2024-01-15",
    "stage": "Active",
    "members": ["Prof. Smith", "Dr. Jones", "Ms. Lee"],
    "description": "Focuses on the theoretical foundations of information and computation and their implementation and application in computer systems.",
    "actions": ["Review Syllabus", "Schedule Meeting"],
    "level": 7,
    "code": "CS101"
  },
  {
    "id": "b2c3d4e5-f6a7-8901-2345-67890abcdef1",
    "faculty": "Faculty of Commerce, Human Sciences and Education",
    "name": "Bachelor of Arts in Psychology",
    "createdDate": "2023-02-20",
    "lastReviewDate": "2024-02-20",
    "stage": "Active",
    "members": ["Prof. Brown", "Dr. Davis", "Mr. Wilson"],
    "description": "Explores the human mind and behavior, applying scientific principles to understand mental processes and social interactions.",
    "actions": ["Update Reading List", "Assign Essays"],
    "level": 6,
    "code": "PS202"
  },
  {
    "id": "c3d4e5f6-a7b8-9012-3456-7890abcdef12",
    "faculty": "Faculty of Health, Natural Resources and Applied Sciences",
    "name": "Bachelor of Science in Environmental Biology",
    "createdDate": "2023-03-25",
    "lastReviewDate": "2024-03-25",
    "stage": "Active",
    "members": ["Prof. Garcia", "Dr. Rodriguez", "Ms. Martinez"],
    "description": "Covers the study of living organisms and their interactions within environmental systems, with a focus on conservation and sustainability.",
    "actions": ["Plan Field Trip", "Conduct Lab Experiment"],
    "level": 7,
    "code": "EB303"
  },
  {
    "id": "d4e5f6a7-b8c9-0123-4567-890abcdef123",
    "faculty": "Faculty of Commerce, Human Sciences and Education",
    "name": "Bachelor of Business Administration in Marketing",
    "createdDate": "2023-04-30",
    "lastReviewDate": "2024-04-30",
    "stage": "Active",
    "members": ["Prof. Williams", "Dr. Anderson", "Mr. Thomas"],
    "description": "Provides a foundation in marketing principles, consumer behavior, and strategic branding.",
    "actions": ["Review Case Studies", "Organize Guest Lecture"],
    "level": 6,
    "code": "BM404"
  },
  {
    "id": "e5f6a7b8-c9d0-1234-5678-abcdef12345",
    "faculty": "Faculty of Health, Natural Resources and Applied Sciences",
    "name": "Bachelor of Science in Public Health",
    "createdDate": "2023-05-05",
    "lastReviewDate": "2024-05-05",
    "stage": "Active",
    "members": ["Prof. Taylor", "Dr. Moore", "Ms. Jackson"],
    "description": "Focuses on improving community health through disease prevention, health promotion, and policy development.",
    "actions": ["Supervise Field Studies", "Conduct Health Research"],
    "level": 7,
    "code": "PH505"
  },
  {
    "id": "f6a7b8c9-d0e1-2345-6789-bcdef123456",
    "faculty": "Faculty of Engineering and the Built Environment",
    "name": "Bachelor of Science in Architectural Studies",
    "createdDate": "2023-06-10",
    "lastReviewDate": "2024-06-10",
    "stage": "Active",
    "members": ["Prof. Clark", "Dr. Lewis", "Mr. Young"],
    "description": "Focuses on the design, planning, and construction of buildings and urban spaces.",
    "actions": ["Review Design Proposals", "Conduct Site Analysis"],
    "level": 7,
    "code": "AS606"
  },
  {
    "id": "a7b8c9d0-e1f2-3456-7890-cdef1234567",
    "faculty": "Faculty of Commerce, Human Sciences and Education",
    "name": "Bachelor of Arts in Education",
    "createdDate": "2023-07-15",
    "lastReviewDate": "2024-07-15",
    "stage": "Active",
    "members": ["Prof. King", "Dr. Wright", "Ms. Hill"],
    "description": "Prepares students for careers in teaching and education, covering pedagogy, curriculum development, and educational psychology.",
    "actions": ["Review Lesson Plans", "Organize Teaching Practicum"],
    "level": 6,
    "code": "ED707"
  },
  {
    "id": "b8c9d0e1-f2a3-4567-8901-def12345678",
    "faculty": "Faculty of Health, Natural Resources and Applied Sciences",
    "name": "Bachelor of Science in Applied Chemistry",
    "createdDate": "2023-08-20",
    "lastReviewDate": "2024-08-20",
    "stage": "Active",
    "members": ["Prof. Green", "Dr. Adams", "Mr. Baker"],
    "description": "Focuses on the practical applications of chemistry in various industries, including pharmaceuticals, materials science, and environmental analysis.",
    "actions": ["Conduct Industrial Analysis", "Review Research Papers"],
    "level": 7,
    "code": "AC808"
  },
  {
    "id": "c9d0e1f2-a3b4-5678-9012-ef123456789",
    "faculty": "Faculty of Commerce, Human Sciences and Education",
    "name": "Master of Business Administration",
    "createdDate": "2023-09-25",
    "lastReviewDate": "2024-09-25",
    "stage": "Active",
    "members": ["Prof. Scott", "Dr. Nelson", "Ms. Carter"],
    "description": "Advanced business management program for experienced professionals, covering strategic leadership, financial management, and organizational behavior.",
    "actions": ["Evaluate Business Plans", "Facilitate Strategic Discussions"],
    "level": 8,
    "code": "MB909"
  },
  {
    "id": "d0e1f2a3-b4c5-6789-0123-f1234567890",
    "faculty": "Faculty of Health, Natural Resources and Applied Sciences",
    "name": "Bachelor of Science in Medical Laboratory Sciences",
    "createdDate": "2023-10-30",
    "lastReviewDate": "2024-10-30",
    "stage": "Active",
    "members": ["Prof. Mitchell", "Dr. Roberts", "Mr. Turner"],
    "description": "Prepares students for careers in medical diagnostics and laboratory analysis, covering hematology, microbiology, and clinical biochemistry.",
    "actions": ["Supervise Laboratory Practice", "Review Diagnostic Reports"],
    "level": 7,
    "code": "ML010"
  },
  {
    "id": "a1b2c3d4-e5f6-7890-1234-567890abcdef",
    "faculty": "Faculty of Computing and Informatics",
    "name": "Bachelor of Science in Computer Science",
    "createdDate": "2023-01-15",
    "lastReviewDate": "2024-01-15",
    "stage": "Active",
    "members": ["Prof. Smith", "Dr. Jones", "Ms. Lee"],
    "description": "Focuses on the theoretical foundations of information and computation and their implementation and application in computer systems.",
    "actions": ["Review Syllabus", "Schedule Meeting"],
    "level": 7,
    "code": "CS101"
  },
  {
    "id": "b2c3d4e5-f6a7-8901-2345-67890abcdef1",
    "faculty": "Faculty of Commerce, Human Sciences and Education",
    "name": "Bachelor of Arts in Psychology",
    "createdDate": "2023-02-20",
    "lastReviewDate": "2024-02-20",
    "stage": "Active",
    "members": ["Prof. Brown", "Dr. Davis", "Mr. Wilson"],
    "description": "Explores the human mind and behavior, applying scientific principles to understand mental processes and social interactions.",
    "actions": ["Update Reading List", "Assign Essays"],
    "level": 6,
    "code": "PS202"
  },
  {
    "id": "c3d4e5f6-a7b8-9012-3456-7890abcdef12",
    "faculty": "Faculty of Health, Natural Resources and Applied Sciences",
    "name": "Bachelor of Science in Environmental Biology",
    "createdDate": "2023-03-25",
    "lastReviewDate": "2024-03-25",
    "stage": "Active",
    "members": ["Prof. Garcia", "Dr. Rodriguez", "Ms. Martinez"],
    "description": "Covers the study of living organisms and their interactions within environmental systems, with a focus on conservation and sustainability.",
    "actions": ["Plan Field Trip", "Conduct Lab Experiment"],
    "level": 7,
    "code": "EB303"
  },
  {
    "id": "d4e5f6a7-b8c9-0123-4567-890abcdef123",
    "faculty": "Faculty of Commerce, Human Sciences and Education",
    "name": "Bachelor of Business Administration in Marketing",
    "createdDate": "2023-04-30",
    "lastReviewDate": "2024-04-30",
    "stage": "Active",
    "members": ["Prof. Williams", "Dr. Anderson", "Mr. Thomas"],
    "description": "Provides a foundation in marketing principles, consumer behavior, and strategic branding.",
    "actions": ["Review Case Studies", "Organize Guest Lecture"],
    "level": 6,
    "code": "BM404"
  },
  {
    "id": "e5f6a7b8-c9d0-1234-5678-abcdef12345",
    "faculty": "Faculty of Health, Natural Resources and Applied Sciences",
    "name": "Bachelor of Science in Public Health",
    "createdDate": "2023-05-05",
    "lastReviewDate": "2024-05-05",
    "stage": "Active",
    "members": ["Prof. Taylor", "Dr. Moore", "Ms. Jackson"],
    "description": "Focuses on improving community health through disease prevention, health promotion, and policy development.",
    "actions": ["Supervise Field Studies", "Conduct Health Research"],
    "level": 7,
    "code": "PH505"
  },
  {
    "id": "f6a7b8c9-d0e1-2345-6789-bcdef123456",
    "faculty": "Faculty of Engineering and the Built Environment",
    "name": "Bachelor of Science in Architectural Studies",
    "createdDate": "2023-06-10",
    "lastReviewDate": "2024-06-10",
    "stage": "Active",
    "members": ["Prof. Clark", "Dr. Lewis", "Mr. Young"],
    "description": "Focuses on the design, planning, and construction of buildings and urban spaces.",
    "actions": ["Review Design Proposals", "Conduct Site Analysis"],
    "level": 7,
    "code": "AS606"
  },
  {
    "id": "a7b8c9d0-e1f2-3456-7890-cdef1234567",
    "faculty": "Faculty of Commerce, Human Sciences and Education",
    "name": "Bachelor of Arts in Education",
    "createdDate": "2023-07-15",
    "lastReviewDate": "2024-07-15",
    "stage": "Active",
    "members": ["Prof. King", "Dr. Wright", "Ms. Hill"],
    "description": "Prepares students for careers in teaching and education, covering pedagogy, curriculum development, and educational psychology.",
    "actions": ["Review Lesson Plans", "Organize Teaching Practicum"],
    "level": 6,
    "code": "ED707"
  },
  {
    "id": "b8c9d0e1-f2a3-4567-8901-def12345678",
    "faculty": "Faculty of Health, Natural Resources and Applied Sciences",
    "name": "Bachelor of Science in Applied Chemistry",
    "createdDate": "2023-08-20",
    "lastReviewDate": "2024-08-20",
    "stage": "Active",
    "members": ["Prof. Green", "Dr. Adams", "Mr. Baker"],
    "description": "Focuses on the practical applications of chemistry in various industries, including pharmaceuticals, materials science, and environmental analysis.",
    "actions": ["Conduct Industrial Analysis", "Review Research Papers"],
    "level": 7,
    "code": "AC808"
  },
  {
    "id": "c9d0e1f2-a3b4-5678-9012-ef123456789",
    "faculty": "Faculty of Commerce, Human Sciences and Education",
    "name": "Master of Business Administration",
    "createdDate": "2023-09-25",
    "lastReviewDate": "2024-09-25",
    "stage": "Active",
    "members": ["Prof. Scott", "Dr. Nelson", "Ms. Carter"],
    "description": "Advanced business management program for experienced professionals, covering strategic leadership, financial management, and organizational behavior.",
    "actions": ["Evaluate Business Plans", "Facilitate Strategic Discussions"],
    "level": 8,
    "code": "MB909"
  },
  {
    "id": "d0e1f2a3-b4c5-6789-0123-f1234567890",
    "faculty": "Faculty of Health, Natural Resources and Applied Sciences",
    "name": "Bachelor of Science in Medical Laboratory Sciences",
    "createdDate": "2023-10-30",
    "lastReviewDate": "2024-10-30",
    "stage": "Active",
    "members": ["Prof. Mitchell", "Dr. Roberts", "Mr. Turner"],
    "description": "Prepares students for careers in medical diagnostics and laboratory analysis, covering hematology, microbiology, and clinical biochemistry.",
    "actions": ["Supervise Laboratory Practice", "Review Diagnostic Reports"],
    "level": 7,
    "code": "ML010"
  },
  {
    "id": "e1f2a3b4-c5d6-7890-1234-1234567890ab",
    "faculty": "Faculty of Engineering and the Built Environment",
    "name": "Bachelor of Science in Mechatronics Engineering",
    "createdDate": "2023-11-05",
    "lastReviewDate": "2024-11-05",
    "stage": "Active",
    "members": ["Prof. Phillips", "Dr. Campbell", "Ms. Parker"],
    "description": "Integrates mechanical, electrical, and computer engineering principles to design and develop automated systems.",
    "actions": ["Review Robotic Designs", "Conduct System Testing"],
    "level": 7,
    "code": "ME111"
  },
  {
    "id": "f2a3b4c5-d6e7-8901-2345-234567890abc",
    "faculty": "Faculty of Computing and Informatics",
    "name": "Bachelor of Information Technology",
    "createdDate": "2023-12-10",
    "lastReviewDate": "2024-12-10",
    "stage": "Active",
    "members": ["Prof. Evans", "Dr. Collins", "Mr. Edwards"],
    "description": "Focuses on the application of technology to solve business and organizational problems, covering software development, network administration, and database management.",
    "actions": ["Review System Designs", "Conduct Network Audits"],
    "level": 6,
    "code": "IT121"
  },
  {
    "id": "a3b4c5d6-e7f8-9012-3456-34567890abcd",
    "faculty": "Faculty of Health, Natural Resources and Applied Sciences",
    "name": "Bachelor of Science in Food Science and Technology",
    "createdDate": "2024-01-15",
    "lastReviewDate": "2025-01-15",
    "stage": "Active",
    "members": ["Prof. Stewart", "Dr. Flores", "Ms. Morris"],
    "description": "Studies the chemical, physical, and biological aspects of food, focusing on food processing, preservation, and quality control.",
    "actions": ["Conduct Food Analysis", "Review Processing Methods"],
    "level": 7,
    "code": "FS131"
  },
  {
    "id": "b4c5d6e7-f8a9-0123-4567-4567890abcde",
    "faculty": "Faculty of Commerce, Human Sciences and Education",
    "name": "Bachelor of Arts in Social Work",
    "createdDate": "2024-02-20",
    "lastReviewDate": "2025-02-20",
    "stage": "Active",
    "members": ["Prof. Gray", "Dr. White", "Ms. Black"],
    "description": "Prepares students for careers in social service, focusing on helping individuals, families, and communities address social problems and improve well-being.",
    "actions": ["Supervise Field Placements", "Conduct Case Reviews"],
    "level": 6,
    "code": "SW141"
  },
  {
    "id": "c5d6e7f8-a9b0-1234-5678-567890abcdef",
    "faculty": "Faculty of Engineering and the Built Environment",
    "name": "Bachelor of Science in Construction Management",
    "createdDate": "2024-03-25",
    "lastReviewDate": "2025-03-25",
    "stage": "Active",
    "members": ["Prof. Hayes", "Dr. Baker", "Mr. Cook"],
    "description": "Focuses on the planning, coordination, and control of construction projects, covering project management, cost estimation, and site operations.",
    "actions": ["Review Construction Plans", "Conduct Site Inspections"],
    "level": 7,
    "code": "CM151"
  },
  {
    "id": "d6e7f8a9-b0c1-2345-6789-67890abcdef1",
    "faculty": "Faculty of Computing and Informatics",
    "name": "Bachelor of Science in Information Systems",
    "createdDate": "2024-04-30",
    "lastReviewDate": "2025-04-30",
    "stage": "Active",
    "members": ["Prof. Rivera", "Dr. Patel", "Ms. Garcia"],
    "description": "Focuses on the design, implementation, and management of information systems to support organizational goals, covering database systems, business analytics, and project management.",
    "actions": ["Review System Specifications", "Conduct Data Analysis"],
    "level": 7,
    "code": "IS161"
  },
  {
    "id": "e7f8a9b0-c1d2-3456-7890-7890abcdef12",
    "faculty": "Faculty of Health, Natural Resources and Applied Sciences",
    "name": "Bachelor of Science in Radiography",
    "createdDate": "2024-05-05",
    "lastReviewDate": "2025-05-05",
    "stage": "Active",
    "members": ["Prof. Murphy", "Dr. Kelly", "Ms. O'Brien"],
    "description": "Prepares students to use imaging technologies to produce diagnostic images of the human body, covering radiography, medical imaging, and patient care.",
    "actions": ["Supervise Clinical Training", "Review Image Quality"],
    "level": 7,
    "code": "RG171"
  },
  {
    "id": "f8a9b0c1-d2e3-4567-8901-8901abcdef123",
    "faculty": "Faculty of Commerce, Human Sciences and Education",
    "name": "Bachelor of Arts in Communication",
    "createdDate": "2024-06-10",
    "lastReviewDate": "2025-06-10",
    "stage": "Active",
    "members": ["Prof. Foster", "Dr. Bennett", "Ms. Perry"],
    "description": "Focuses on the study of human communication, including interpersonal communication, media studies, and public relations.",
    "actions": ["Review Communication Plans", "Evaluate Presentations"],
    "level": 6,
    "code": "CM181"
  },
  {
    "id": "a9b0c1d2-e3f4-5678-9012-9012abcdef1234",
    "faculty": "Faculty of Engineering and the Built Environment",
    "name": "Bachelor of Science in Quantity Surveying",
    "createdDate": "2024-07-15",
    "lastReviewDate": "2025-07-15",
    "stage": "Active",
    "members": ["Prof. Simmons", "Dr. Coleman", "Mr. Ross"],
    "description": "Focuses on the management of construction costs and contracts, covering cost estimation, procurement, and contract administration.",
    "actions": ["Review Cost Estimates", "Evaluate Tender Documents"],
    "level": 7,
    "code": "QS191"
  },
  {
    "id": "b0c1d2e3-f4a5-6789-0123-0123abcdef12345",
    "faculty": "Faculty of Computing and Informatics",
    "name": "Bachelor of Science in Software Engineering",
    "createdDate": "2024-08-20",
    "lastReviewDate": "2025-08-20",
    "stage": "Active",
    "members": ["Prof. Alexander", "Dr. Mitchell", "Ms. Harris"],
    "description": "Focuses on the design, development, testing, and maintenance of software systems, covering software architecture, programming, and software quality assurance.",
    "actions": ["Review Software Designs", "Conduct Code Reviews"],
    "level": 7,
    "code": "SE201"
  },
  {
    "id": "a1b2c3d4-e5f6-7890-1234-567890abcdef",
    "faculty": "Faculty of Computing and Informatics",
    "name": "Bachelor of Science in Computer Science",
    "createdDate": "2023-01-15",
    "lastReviewDate": "2024-01-15",
    "stage": "Active",
    "members": ["Prof. Smith", "Dr. Jones", "Ms. Lee"],
    "description": "Focuses on the theoretical foundations of information and computation and their implementation and application in computer systems.",
    "actions": ["Review Syllabus", "Schedule Meeting"],
    "level": 7,
    "code": "CS101"
  },
  {
    "id": "b2c3d4e5-f6a7-8901-2345-67890abcdef1",
    "faculty": "Faculty of Commerce, Human Sciences and Education",
    "name": "Bachelor of Arts in Psychology",
    "createdDate": "2023-02-20",
    "lastReviewDate": "2024-02-20",
    "stage": "Active",
    "members": ["Prof. Brown", "Dr. Davis", "Mr. Wilson"],
    "description": "Explores the human mind and behavior, applying scientific principles to understand mental processes and social interactions.",
    "actions": ["Update Reading List", "Assign Essays"],
    "level": 6,
    "code": "PS202"
  },
  {
    "id": "c3d4e5f6-a7b8-9012-3456-7890abcdef12",
    "faculty": "Faculty of Health, Natural Resources and Applied Sciences",
    "name": "Bachelor of Science in Environmental Biology",
    "createdDate": "2023-03-25",
    "lastReviewDate": "2024-03-25",
    "stage": "Active",
    "members": ["Prof. Garcia", "Dr. Rodriguez", "Ms. Martinez"],
    "description": "Covers the study of living organisms and their interactions within environmental systems, with a focus on conservation and sustainability.",
    "actions": ["Plan Field Trip", "Conduct Lab Experiment"],
    "level": 7,
    "code": "EB303"
  },
  {
    "id": "d4e5f6a7-b8c9-0123-4567-890abcdef123",
    "faculty": "Faculty of Commerce, Human Sciences and Education",
    "name": "Bachelor of Business Administration in Marketing",
    "createdDate": "2023-04-30",
    "lastReviewDate": "2024-04-30",
    "stage": "Active",
    "members": ["Prof. Williams", "Dr. Anderson", "Mr. Thomas"],
    "description": "Provides a foundation in marketing principles, consumer behavior, and strategic branding.",
    "actions": ["Review Case Studies", "Organize Guest Lecture"],
    "level": 6,
    "code": "BM404"
  },
  {
    "id": "e5f6a7b8-c9d0-1234-5678-abcdef12345",
    "faculty": "Faculty of Health, Natural Resources and Applied Sciences",
    "name": "Bachelor of Science in Public Health",
    "createdDate": "2023-05-05",
    "lastReviewDate": "2024-05-05",
    "stage": "Active",
    "members": ["Prof. Taylor", "Dr. Moore", "Ms. Jackson"],
    "description": "Focuses on improving community health through disease prevention, health promotion, and policy development.",
    "actions": ["Supervise Field Studies", "Conduct Health Research"],
    "level": 7,
    "code": "PH505"
  },
  {
    "id": "f6a7b8c9-d0e1-2345-6789-bcdef123456",
    "faculty": "Faculty of Engineering and the Built Environment",
    "name": "Bachelor of Science in Architectural Studies",
    "createdDate": "2023-06-10",
    "lastReviewDate": "2024-06-10",
    "stage": "Active",
    "members": ["Prof. Clark", "Dr. Lewis", "Mr. Young"],
    "description": "Focuses on the design, planning, and construction of buildings and urban spaces.",
    "actions": ["Review Design Proposals", "Conduct Site Analysis"],
    "level": 7,
    "code": "AS606"
  },
  {
    "id": "a7b8c9d0-e1f2-3456-7890-cdef1234567",
    "faculty": "Faculty of Commerce, Human Sciences and Education",
    "name": "Bachelor of Arts in Education",
    "createdDate": "2023-07-15",
    "lastReviewDate": "2024-07-15",
    "stage": "Active",
    "members": ["Prof. King", "Dr. Wright", "Ms. Hill"],
    "description": "Prepares students for careers in teaching and education, covering pedagogy, curriculum development, and educational psychology.",
    "actions": ["Review Lesson Plans", "Organize Teaching Practicum"],
    "level": 6,
    "code": "ED707"
  },
  {
    "id": "b8c9d0e1-f2a3-4567-8901-def12345678",
    "faculty": "Faculty of Health, Natural Resources and Applied Sciences",
    "name": "Bachelor of Science in Applied Chemistry",
    "createdDate": "2023-08-20",
    "lastReviewDate": "2024-08-20",
    "stage": "Active",
    "members": ["Prof. Green", "Dr. Adams", "Mr. Baker"],
    "description": "Focuses on the practical applications of chemistry in various industries, including pharmaceuticals, materials science, and environmental analysis.",
    "actions": ["Conduct Industrial Analysis", "Review Research Papers"],
    "level": 7,
    "code": "AC808"
  },
  {
    "id": "c9d0e1f2-a3b4-5678-9012-ef123456789",
    "faculty": "Faculty of Commerce, Human Sciences and Education",
    "name": "Master of Business Administration",
    "createdDate": "2023-09-25",
    "lastReviewDate": "2024-09-25",
    "stage": "Active",
    "members": ["Prof. Scott", "Dr. Nelson", "Ms. Carter"],
    "description": "Advanced business management program for experienced professionals, covering strategic leadership, financial management, and organizational behavior.",
    "actions": ["Evaluate Business Plans", "Facilitate Strategic Discussions"],
    "level": 8,
    "code": "MB909"
  },
  {
    "id": "d0e1f2a3-b4c5-6789-0123-f1234567890",
    "faculty": "Faculty of Health, Natural Resources and Applied Sciences",
    "name": "Bachelor of Science in Medical Laboratory Sciences",
    "createdDate": "2023-10-30",
    "lastReviewDate": "2024-10-30",
    "stage": "Active",
    "members": ["Prof. Mitchell", "Dr. Roberts", "Mr. Turner"],
    "description": "Prepares students for careers in medical diagnostics and laboratory analysis, covering hematology, microbiology, and clinical biochemistry.",
    "actions": ["Supervise Laboratory Practice", "Review Diagnostic Reports"],
    "level": 7,
    "code": "ML010"
  },
  {
    "id": "e1f2a3b4-c5d6-7890-1234-1234567890ab",
    "faculty": "Faculty of Engineering and the Built Environment",
    "name": "Bachelor of Science in Mechatronics Engineering",
    "createdDate": "2023-11-05",
    "lastReviewDate": "2024-11-05",
    "stage": "Active",
    "members": ["Prof. Phillips", "Dr. Campbell", "Ms. Parker"],
    "description": "Integrates mechanical, electrical, and computer engineering principles to design and develop automated systems.",
    "actions": ["Review Robotic Designs", "Conduct System Testing"],
    "level": 7,
    "code": "ME111"
  },
  {
    "id": "f2a3b4c5-d6e7-8901-2345-234567890abc",
    "faculty": "Faculty of Computing and Informatics",
    "name": "Bachelor of Information Technology",
    "createdDate": "2023-12-10",
    "lastReviewDate": "2024-12-10",
    "stage": "Active",
    "members": ["Prof. Evans", "Dr. Collins", "Mr. Edwards"],
    "description": "Focuses on the application of technology to solve business and organizational problems, covering software development, network administration, and database management.",
    "actions": ["Review System Designs", "Conduct Network Audits"],
    "level": 6,
    "code": "IT121"
  },
  {
    "id": "a3b4c5d6-e7f8-9012-3456-34567890abcd",
    "faculty": "Faculty of Health, Natural Resources and Applied Sciences",
    "name": "Bachelor of Science in Food Science and Technology",
    "createdDate": "2024-01-15",
    "lastReviewDate": "2025-01-15",
    "stage": "Active",
    "members": ["Prof. Stewart", "Dr. Flores", "Ms. Morris"],
    "description": "Studies the chemical, physical, and biological aspects of food, focusing on food processing, preservation, and quality control.",
    "actions": ["Conduct Food Analysis", "Review Processing Methods"],
    "level": 7,
    "code": "FS131"
  },
  {
    "id": "b4c5d6e7-f8a9-0123-4567-4567890abcde",
    "faculty": "Faculty of Commerce, Human Sciences and Education",
    "name": "Bachelor of Arts in Social Work",
    "createdDate": "2024-02-20",
    "lastReviewDate": "2025-02-20",
    "stage": "Active",
    "members": ["Prof. Gray", "Dr. White", "Ms. Black"],
    "description": "Prepares students for careers in social service, focusing on helping individuals, families, and communities address social problems and improve well-being.",
    "actions": ["Supervise Field Placements", "Conduct Case Reviews"],
    "level": 6,
    "code": "SW141"
  },
  {
    "id": "c5d6e7f8-a9b0-1234-5678-567890abcdef",
    "faculty": "Faculty of Engineering and the Built Environment",
    "name": "Bachelor of Science in Construction Management",
    "createdDate": "2024-03-25",
    "lastReviewDate": "2025-03-25",
    "stage": "Active",
    "members": ["Prof. Hayes", "Dr. Baker", "Mr. Cook"],
    "description": "Focuses on the planning, coordination, and control of construction projects, covering project management, cost estimation, and site operations.",
    "actions": ["Review Construction Plans", "Conduct Site Inspections"],
    "level": 7,
    "code": "CM151"
  },
  {
    "id": "d6e7f8a9-b0c1-2345-6789-67890abcdef1",
    "faculty": "Faculty of Computing and Informatics",
    "name": "Bachelor of Science in Information Systems",
    "createdDate": "2024-04-30",
    "lastReviewDate": "2025-04-30",
    "stage": "Active",
    "members": ["Prof. Rivera", "Dr. Patel", "Ms. Garcia"],
    "description": "Focuses on the design, implementation, and management of information systems to support organizational goals, covering database systems, business analytics, and project management.",
    "actions": ["Review System Specifications", "Conduct Data Analysis"],
    "level": 7,
    "code": "IS161"
  },
  {
    "id": "e7f8a9b0-c1d2-3456-7890-7890abcdef12",
    "faculty": "Faculty of Health, Natural Resources and Applied Sciences",
    "name": "Bachelor of Science in Radiography",
    "createdDate": "2024-05-05",
    "lastReviewDate": "2025-05-05",
    "stage": "Active",
    "members": ["Prof. Murphy", "Dr. Kelly", "Ms. O'Brien"],
    "description": "Prepares students to use imaging technologies to produce diagnostic images of the human body, covering radiography, medical imaging, and patient care.",
    "actions": ["Supervise Clinical Training", "Review Image Quality"],
    "level": 7,
    "code": "RG171"
  },
  {
    "id": "f8a9b0c1-d2e3-4567-8901-8901abcdef123",
    "faculty": "Faculty of Commerce, Human Sciences and Education",
    "name": "Bachelor of Arts in Communication",
    "createdDate": "2024-06-10",
    "lastReviewDate": "2025-06-10",
    "stage": "Active",
    "members": ["Prof. Foster", "Dr. Bennett", "Ms. Perry"],
    "description": "Focuses on the study of human communication, including interpersonal communication, media studies, and public relations.",
    "actions": ["Review Communication Plans", "Evaluate Presentations"],
    "level": 6,
    "code": "CM181"
  },
  {
    "id": "a9b0c1d2-e3f4-5678-9012-9012abcdef1234",
    "faculty": "Faculty of Engineering and the Built Environment",
    "name": "Bachelor of Science in Quantity Surveying",
    "createdDate": "2024-07-15",
    "lastReviewDate": "2025-07-15",
    "stage": "Active",
    "members": ["Prof. Simmons", "Dr. Coleman", "Mr. Ross"],
    "description": "Focuses on the management of construction costs and contracts, covering cost estimation, procurement, and contract administration.",
    "actions": ["Review Cost Estimates", "Evaluate Tender Documents"],
    "level": 7,
    "code": "QS191"
  },
  {
    "id": "b0c1d2e3-f4a5-6789-0123-0123abcdef12345",
    "faculty": "Faculty of Computing and Informatics",
    "name": "Bachelor of Science in Software Engineering",
    "createdDate": "2024-08-20",
    "lastReviewDate": "2025-08-20",
    "stage": "Active",
    "members": ["Prof. Alexander", "Dr. Mitchell", "Ms. Harris"],
    "description": "Focuses on the design, development, testing, and maintenance of software systems, covering software architecture, programming, and software quality assurance.",
    "actions": ["Review Software Designs", "Conduct Code Reviews"],
    "level": 7,
    "code": "SE201"
  }
];




export const NQFLevel: number[] = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10];
